# Generated by Django 3.2.9 on 2021-12-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
    ]
