# Generated by Django 3.2.9 on 2021-12-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20211212_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
    ]
