# Generated by Django 3.2.9 on 2021-12-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_imagen_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='imagen',
        ),
    ]
