# Generated by Django 3.2.9 on 2021-12-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_rename_image_profile_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='image',
        ),
    ]
