# Generated by Django 3.2.9 on 2021-12-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_rename_imagen_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='SEX', upload_to=''),
            preserve_default=False,
        ),
    ]
