# Generated by Django 4.0 on 2021-12-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20211215_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
